name: Analyze

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Install dependencies
      run: dotnet restore .\FlashCard.sln

    - name: Run build
      run: dotnet build .\FlashCard.sln --no-restore /p:RunAnalyzersDuringBuild=true /p:RunCodeAnalysis=true
